# Generated by Django 4.0.2 on 2022-07-23 15:30

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=64)),
                ('SNN', models.CharField(max_length=64)),
                ('major', models.CharField(max_length=64)),
                ('degree', models.CharField(max_length=64)),
                ('university', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=2048)),
                ('status', models.CharField(max_length=64)),
                ('field', models.CharField(max_length=64, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=64)),
                ('judges', models.CharField(blank=True, max_length=64)),
                ('language', models.CharField(max_length=64)),
                ('NOM', models.CharField(max_length=64)),
                ('field', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=512, unique=True)),
                ('summary', models.TextField()),
                ('paperFile', models.FileField(max_length=254, upload_to='papers/')),
                ('MOP', models.CharField(max_length=64)),
                ('published', models.BooleanField(default=False, null=True)),
                ('dabirKhane', models.BooleanField(default=False, null=True)),
                ('dabirBakhsh', models.BooleanField(default=False, null=True)),
                ('dabirKonferans', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.IntegerField(blank=True, null=True)),
                ('q2', models.IntegerField(blank=True, null=True)),
                ('q3', models.IntegerField(blank=True, null=True)),
                ('q4', models.IntegerField(blank=True, null=True)),
                ('q5', models.IntegerField(blank=True, null=True)),
                ('q6', models.IntegerField(blank=True, null=True)),
                ('q7', models.IntegerField(blank=True, null=True)),
                ('q8', models.IntegerField(blank=True, null=True)),
                ('q9', models.IntegerField(blank=True, null=True)),
                ('q10', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=2048)),
                ('judge', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='judge', to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='paper', to='mainApp.paper')),
            ],
        ),
        migrations.AddField(
            model_name='baseuser',
            name='judgePapers',
            field=models.ManyToManyField(blank=True, related_name='judgePapers', to='mainApp.Paper'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='userPapers',
            field=models.ManyToManyField(blank=True, related_name='userPapers', to='mainApp.Paper'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
