# Generated by Django 4.0.2 on 2022-07-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paperFile',
            field=models.FileField(max_length=254, upload_to='papers/'),
        ),
    ]
