# Generated by Django 4.0.2 on 2022-07-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_paper_paperfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
