# Generated by Django 4.0.2 on 2022-07-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_feedback_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='dabirKonferans',
            new_name='dabirConference',
        ),
    ]
