# Generated by Django 4.0.2 on 2022-07-06 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_paper_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=2048)),
                ('judge', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='judge', to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='paper', to='mainApp.paper')),
            ],
        ),
    ]
