# Generated by Django 4.0.2 on 2022-07-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_rename_dabirkonferans_paper_dabirconference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='dabirBakhsh',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='dabirConference',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='dabirKhane',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='published',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
