# Generated by Django 4.0.2 on 2022-07-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_paper_dabirbakhsh_alter_paper_dabirconference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='subfields',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='subfields',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
