# Generated by Django 4.0.2 on 2022-07-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_paper_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='field',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
