# Generated by Django 4.0.2 on 2022-07-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_baseuser_subfields_paper_subfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='accepted',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
