# Generated by Django 4.0.2 on 2022-07-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_baseuser_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='judges',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
