# Generated by Django 4.0.2 on 2022-07-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_feedback_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='dabirBakhsh',
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='dabirConference',
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='dabirKhane',
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='published',
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
    ]
