# Generated by Django 4.0.2 on 2022-07-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_remove_feedback_q1_remove_feedback_q10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='dateAccepted',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='dateAssigned',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
