# Generated by Django 4.0.2 on 2022-07-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_alter_feedback_dateaccepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='timeLeft',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
