# Generated by Django 4.0.2 on 2022-08-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_paper_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='daysLeft',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='paper',
            name='scores',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
