# Generated by Django 4.0.2 on 2022-08-03 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_paper_daysleft_paper_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='daysLeft',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='judges',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='scores',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='status',
        ),
    ]
