# Generated by Django 4.0.2 on 2022-08-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_alter_paper_dabirbakhsh_alter_paper_dabirkhane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='dabirConference',
            field=models.CharField(blank=True, default=None, max_length=2048, null=True),
        ),
    ]
